export enum GenreData {
  Rock = "Rock",
  Pop = "Pop",
  Jazz = "Jazz",
  Classical = "Classical",
  HipHop = "Hip Hop",
  Electronic = "Electronic",
  Blues = "Blues",
  Country = "Country",
  Folk = "Folk",
  Reggae = "Reggae",
  Latin = "Latin",
  World = "World",
  Other = "Other",
}
